export const data = {
  home: {
    categories: [
      {
        id: 1,
        icon: './images/category/Phone.png',
        name: 'Category Name',
        items: '2.3k items',
        selected: true,
      },
      {
        id: 2,
        icon: './images/category/Camera.png',
        name: 'Category Name',
        items: '2.3k items',
        selected: false,
      },
      {
        id: 3,
        icon: './images/category/Computer.png',
        name: 'Category Name',
        items: '2.3k items',
        selected: false,
      },
      {
        id: 4,
        icon: './images/category/Mens fashion.png', // hoặc tên custom, như "fa-tank-top" nếu là SVG riêng
        name: 'Category Name',
        items: '2.3k items',
        selected: false,
      },
      {
        id: 5,
        icon: './images/category/Games.png',
        name: 'Category Name',
        items: '2.3k items',
        selected: false,
      },
      {
        id: 6,
        icon: './images/category/Healthy.png',
        name: 'Category Name',
        items: '2.3k items',
        selected: false,
      },
    ],
    productLists: [
      {
        id: 1,
        title: 'Product list 1',
        products: [
          {
            id: 101,
            image: 'images/iphone.png',
            name: 'Popular items from cat 01',
            price: 1725.0,
            rating: 4.6,
          },
          {
            id: 102,
            image: 'images/iphone.png',
            name: 'Popular items from cat 01',
            price: 1725.0,
            rating: 4.6,
          },
          {
            id: 103,
            image: 'images/iphone.png',
            name: 'Popular items from cat 01',
            price: 1725.0,
            rating: 4.6,
          },
        ],
        viewMoreLink: '/products/list-1',
      },
      {
        id: 2,
        title: 'Product list 2',
        products: [
          {
            id: 201,
            image: 'images/clock.png',
            name: 'Popular items from cat 02',
            price: 1725.0,
            rating: 4.6,
          },
          {
            id: 202,
            image: 'images/clock.png',
            name: 'Popular items from cat 02',
            price: 1725.0,
            rating: 4.6,
          },
          {
            id: 203,
            image: 'images/clock.png',
            name: 'Popular items from cat 02',
            price: 1725.0,
            rating: 4.6,
          },
        ],
        viewMoreLink: '/products/list-2',
      },
      {
        id: 3,
        title: 'Product list 3',
        products: [
          {
            id: 301,
            image: 'images/sweat.png',
            name: 'Popular items from cat 03',
            price: 1725.0,
            rating: 4.6,
          },
          {
            id: 302,
            image: 'images/sweat.png',
            name: 'Popular items from cat 03',
            price: 1725.0,
            rating: 4.6,
          },
          {
            id: 303,
            image: 'images/sweat.png',
            name: 'Popular items from cat 03',
            price: 1725.0,
            rating: 4.6,
          },
        ],
        viewMoreLink: '/products/list-3',
      },
    ],
    blog: {
      header: {
        heading: 'Read our blog',
        description:
          'Check our latest article to get meaningfull content or tips for shopping',
      },
      blogPosts: [
        {
          id: 1,
          image: 'images/Blogitem1.png',
          date: '07 July 2020',
          title: 'Types of Blouse In Catalog fashion',
          description:
            'In order to discuss the general function of the logo, we must firstly identify and define the environment…',
          selected: true,
        },
        {
          id: 2,
          image: 'images/Blogitem2.png',
          date: '08 July 2020',
          title: 'Types of Blouse In Catalog fashion',
          description:
            'In order to discuss the general function of the logo, we must firstly identify and define the environment…',
          selected: false,
        },
        {
          id: 3,
          image: 'images/Blogitem3.png',
          date: '09 July 2020',
          title: 'Types of Blouse In Catalog fashion',
          description:
            'In order to discuss the general function of the logo, we must firstly identify and define the environment…',
          selected: false,
        },
      ],
    },
  },
  category: {
    header: {
      heading: 'Shop categories',
      description: 'Check all our categories to get what brand you needs',
    },
    productLists: [
      {
        id: 1,
        background: 'bg-teal/10',
        image: 'images/Category1.png',
        title: 'Product list 1',
        items: '2,3k items',
        itemsColor: 'teal',
        categories: [
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
        ],
      },
      {
        id: 2,
        background: 'bg-green/10',
        image: 'images/Category2.png',
        title: 'Product list 1',
        items: '2,3k items',
        itemsColor: 'green',
        categories: [
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
        ],
      },
      {
        id: 3,
        background: 'bg-orange/10',
        image: 'images/Category3.png',
        title: 'Product list 1',
        items: '2,3k items',
        itemsColor: 'red',
        categories: [
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
        ],
      },
      {
        id: 4,
        background: 'bg-yellow/10',
        image: 'images/Category4.png',
        title: 'Product list 1',
        items: '2,3k items',
        itemsColor: 'yellow',
        categories: [
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
        ],
      },
      {
        id: 5,
        background: 'bg-purple/10',
        image: 'images/Category5.png',
        title: 'Product list 1',
        items: '2,3k items',
        itemsColor: 'purple',
        categories: [
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
        ],
      },
      {
        id: 6,
        background: 'bg-blue/10',
        image: 'images/Category6.png',
        title: 'Product list 1',
        items: '2,3k items',
        itemsColor: 'blue',
        categories: [
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
          { name: 'Category Name', quantity: 124 },
        ],
      },
    ],
    brand: {
      heading: 'Popular Brands',
      description: 'Check our best seller products on Elma website right now',
    },
    brandLists: [
      {
        id: 1,
        brand_name: 'Apple',
        background: 'white',
        logo: 'images/brands/Apple.png',
      },
      {
        id: 2,
        brand_name: 'Xiaomi',
        background: 'orange',
        logo: 'images/brands/Xiaomi.png',
      },
      {
        id: 3,
        brand_name: 'Wacom',
        background: 'green/10',
        logo: 'images/brands/Wacom.png',
      },
      {
        id: 4,
        brand_name: 'Asus',
        background: 'blue',
        logo: 'images/brands/Asus.png',
      },
      {
        id: 5,
        brand_name: 'Sony',
        background: 'orange/10',
        logo: 'images/brands/Sony.png',
      },
      {
        id: 6,
        brand_name: 'Barbour',
        background: 'purple',
        logo: 'images/brands/Barbour.png',
      },
      {
        id: 7,
        brand_name: 'Samsung',
        background: 'blue',
        logo: 'images/brands/Samsung.png',
      },
      {
        id: 8,
        brand_name: 'Fila',
        background: 'purple/20',
        logo: 'images/brands/Fila.png',
      },
    ],
  },
};
